"""initial schema

Revision ID: 1144f4016923
Revises: 
Create Date: 2026-06-20 11:10:22.663689

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1144f4016923'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_fetched', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index('ix_sources_enabled', ['enabled'], unique=False)

    op.create_table('seeds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seeds', schema=None) as batch_op:
        batch_op.create_index('ix_seeds_status', ['status'], unique=False)

    op.create_table('ideas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seed_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.create_index('ix_ideas_status', ['status'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('idea_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('publish_error', sa.Text(), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=False),
    sa.Column('media_paths', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index('ix_drafts_platform', ['platform'], unique=False)
        batch_op.create_index('ix_drafts_scheduled_at', ['scheduled_at'], unique=False)
        batch_op.create_index('ix_drafts_status', ['status'], unique=False)

    op.create_table('published',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('published')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_drafts_status')
        batch_op.drop_index('ix_drafts_scheduled_at')
        batch_op.drop_index('ix_drafts_platform')

    op.drop_table('drafts')
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_index('ix_ideas_status')

    op.drop_table('ideas')
    with op.batch_alter_table('seeds', schema=None) as batch_op:
        batch_op.drop_index('ix_seeds_status')

    op.drop_table('seeds')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('ix_sources_enabled')

    op.drop_table('sources')
    # ### end Alembic commands ###
